#!/bin/sh

set -e

case "$1" in
    configure)
	if [ -x /usr/bin/apt-key ]; then
	    apt-key add /usr/share/keyrings/zultron-keyring.gpg
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
